version: '3.5'
services:
  composer:
    restart: 'no'
    container_name: istart_composer
    image: composer:latest
    command: install --ignore-platform-reqs
    volumes:
      - .:/app/
  istart:
    container_name: istart
    build:
      context: .
      target: base
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - composer
